#cargo-features = ["edition2021"]

[package]
name = "economy3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0"
rand="0"
num-traits="^0"
amd64_timer="1.3.0"
